POST https://videos-api-5ypx.onrender.com/videos
Content-Type: application/json
Accept-Language: en

{
  "title": "Video Node",
  "description": "Video 1 description",
  "url": "https://www.youtube.com/watch?v=1",
  "duration": 100
}

###

GET https://videos-api-5ypx.onrender.com/videos?search=

###

PUT https://videos-api-5ypx.onrender.com/videos/53da5817-02d4-47af-8558-44c50bae1808
Content-Type: application/json
Accept-Language: en

{
  "title": "Video 01",
  "description": "Video 1 description",
  "url": "https://www.youtube.com/watch?v=1",
  "duration": 100
}

###

DELETE https://videos-api-5ypx.onrender.com/videos/53da5817-02d4-47af-8558-44c50bae1808